# Generated by Django 4.2.28 on 2026-06-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitylog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.DeleteModel(
            name="SystemSettings",
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
