# Generated by Django 6.0.1 on 2026-01-08 01:38

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("tasks_created", models.PositiveIntegerField(default=0)),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                ("tasks_overdue", models.PositiveIntegerField(default=0)),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "productivity_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calculated productivity score based on various metrics",
                        max_digits=5,
                    ),
                ),
                (
                    "categories_data",
                    models.JSONField(
                        default=dict,
                        help_text="Category-wise task distribution and completion data",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Stats",
                "verbose_name_plural": "Daily Stats",
                "db_table": "analytics_daily_stats",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="analytics_d_user_id_c4a930_idx"
                    ),
                    models.Index(fields=["date"], name="analytics_d_date_26c219_idx"),
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("week_number", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_tasks_created", models.PositiveIntegerField(default=0)),
                ("total_tasks_completed", models.PositiveIntegerField(default=0)),
                ("total_tasks_overdue", models.PositiveIntegerField(default=0)),
                (
                    "total_hours_worked",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "average_productivity_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "weekly_categories_data",
                    models.JSONField(
                        default=dict, help_text="Weekly aggregated category data"
                    ),
                ),
                (
                    "daily_breakdown",
                    models.JSONField(
                        default=list, help_text="Daily stats breakdown for the week"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Stats",
                "verbose_name_plural": "Weekly Stats",
                "db_table": "analytics_weekly_stats",
                "ordering": ["-year", "-week_number"],
                "indexes": [
                    models.Index(
                        fields=["user", "year", "week_number"],
                        name="analytics_w_user_id_4af08c_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="analytics_w_start_d_aa978d_idx",
                    ),
                ],
                "unique_together": {("user", "year", "week_number")},
            },
        ),
    ]
