# Generated by Django 4.2.28 on 2026-06-20 11:15

from django.db import migrations, models


def migrate_pending_to_todo(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Task.objects.filter(status='pending').update(status='todo')


def reverse_migrate_todo_to_pending(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    Task.objects.filter(status='todo').update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_pending_to_todo, reverse_migrate_todo_to_pending),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "Todo"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
